name: PR Cleanup

on:
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello  ${{ github.event.pull_request.head.label }} ${{ github.event.pull_request.head.ref }}
